name: auto_reload
version: 1.0.2
description: A library that helps to perform actions with some periodicity
repository: "https://github.com/surfstudio/flutter-auto-reload/"
issue_tracker: "https://github.com/surfstudio/flutter-auto-reload/issues"

dependencies:
  connectivity_plus: ^2.2.1
  flutter:
    sdk: flutter

dev_dependencies:
  fake_async: ^1.2.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  surf_lint_rules: ^1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
